### PR TITLE
Sanitize metadata from usage CRD

### PR DESCRIPTION
**Pull request by smarlowucf**
- Drop Usage tuple and use dict
- Cleanup flake8 formatting

### CODE REVIEW

**Review by KeithMnemonic — COMMENTED** [review]
LGTM but I am not sure I understand what/why you are santizing. Could you add some additional context to the comment on line 185?

**Comment by smarlowucf** [comment]
> not sure I understand what/why you are santizing

CRD response includes k8s specific metadata in the dictionary. We clean up / sanitize this before passing it back to core app. This leaves only the usage data for the given product.

**Comment by smarlowucf** [comment]
Added more comments to clarify details.

**Review by brett060102 — APPROVED** [review]
Looks good.

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Review by rtamalin — APPROVED** [review]
LGTM

**Pull request merged**
